[package]
edition = "2021"
name = "rust_tech"
version = "1.0.0"
authors = ["栈烟 <zhanyan.work@outlook.com>"]
keywords = ["NoobCode"]
include = [
    "/Cargo.toml",
    "/src/**"
]

[profile.dev]
opt-level = 1
codegen-units = 64

[dependencies]
rand = "0.8.5"