[source.crates-io]
replace-with = 'rsproxy-sparse'
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"
[net]
git-fetch-with-cli = true

#   Please set these system variable

#RUSTUP_DIST_SERVER="https://rsproxy.cn"
#RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"